version: '3.4'

services:
  catalogdb:
    image: mongo
    
  # alpine with redis will be used as it takes less space
  basketdb:
    image: redis:alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  mongo_data:    
