version: '3.4'

services:

  # mongo db image for docker in catalog api
  catalogdb:
    image: mongo
    
  # redis db image for docker in basket api
  # alpine with redis will be used as it takes less space
  basketdb:
    image: redis:alpine

  # postgres db image for docker in discount api
  # alpine with redis will be used as it takes less space
  discountdb:
    image: postgres:alpine

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
  mongo_data:    
  portainer_data:
  postgres_data:  
  pgadmin_data:  

